### ISSUE TITLE
How to make an array of symbols for limited depth stream?

### ISSUE THREAD

**Issue by allawitte** [Ashlar/binance-api-node#121]
I send a request like:

```
binance.ws.partialDepth([{ symbol: 'XMRBTC', level: 10 }, { symbol: 'ARNBTC', level: 10 }], depth => {
  console.log(depth)
})
```

and get the error:  `WebSocket closed: 3067830576 (1008) {"code":-1,"msg":"Illegal format ws or stream"}`

And then some stream with expected data. Why do I get this error?

**Comment by balthazar** [comment]
This should work, have you tried again recently?
