### ISSUE TITLE
Msg socket disconnections without any error.

### ISSUE THREAD

**Issue by numerized** [Ashlar/binance-api-node#123]
Hi friends

It has been few days that I experience again socket disconnections.

I am on 
```"binance-api-node": "^0.8.4"```§

Here's my code basically it works few hours and then nothing no more msg from the socket.

```
// STARTING USER MESSAGING SOCKETS
startUserMsgSocket = () => {

	userMsgSocket = client.ws.user(msg => {

		// we update live wallet on receiving account eventType
		if(msg.eventType == 'account') {
			updateLiveWallet(msg.balances);
		}
}
```

_Originally posted by @numerized in https://github.com/HyperCubeProject/binance-api-node/issue_comments#issuecomment-433031750_

**Comment by numerized** [comment]
Do you think it can be related to this:
https://github.com/HyperCubeProject/binance-api-node/issues/110

**Comment by numerized** [comment]
Awesome! Thanks

**Comment by numerized** [comment]
Still socket disconnecting brother.
tHanks

**Comment by numerized** [comment]
I'm talking here about user.msg socket.

**Comment by numerized** [comment]
The funny thing is that I tried to forcekill the socket and establish again every 15min but it still hangs after a while... Could it be something from Binance side if we are too agressive? I have only little knowledge about socket.

**Comment by numerized** [comment]
And again socket won't reconnect auto, even if clean() method is called with setInterval and relaunched.

**Comment by numerized** [comment]
It works like for 24hours and then stops...
I really need your input on this, the user msg socket is key...

**Comment by ManuCart** [comment]
I have been this issues may be 6 month ago.
After investigate, it was my personnal network who disconneted the socket.
The socket need at least suficient network band to work.
Please try again without using your personnal network for youtube, tv, upload... more than 24hours
It should be too your script who gave not sufficiant time to the socket.
Try and tell me

**Comment by numerized** [comment]
I am on a dedicated server on a very powerful rack and superfast bandwidth.
It was working perfectly before the socket code changes have been made.

How my script could give not sufficient time to the socket I'm just calling the promise. Can you be more specific ?

**Comment by numerized** [comment]
Look at this:

https://github.com/HyperCubeProject/binance-api-node/pull/124

**Comment by ManuCart** [comment]
What sort of socket code change, may be same issue for me because not update between 6 months.
but I'm using ````binance-api-node@0.8.5````
I'm using ````client.ws.partialDepth`````and ````client.ws.candles```` without deconnection
sample of my code
````
binance.ws.candles(PAIRS, '1m', candle => {
    if (candle.isFinal == true) {
    var json = {'E': parseInt(candle.eventTime), "o": parseFloat(candle.open), "l": parseFloat(candle.low),.
                "h": parseFloat(candle.high), "c": parseFloat(candle.close), "v": parseFloat(candle.volume)};
    decision(candle.symbol,json)
    }
 })
````

**Comment by numerized** [comment]
cool I have no problem actually with those sockets.
It's the client.ws.user that causes problems but I'm trying the #124 branch.

Thanks again!

**Comment by beratuslu** [comment]
@numerized what is the result now? Is it reliable now?

Thank you.
