### ISSUE TITLE
trades and candles websockets disconnecting after 60m

### ISSUE THREAD

**Issue by subos2008** [Ashlar/binance-api-node#131]
I'm finding my node processes using `ws.candles` and `ws.trades` are exiting after 60m.

I notice that Binance's API required a keep alive every 60m - but it sounds like you have implemented a constant keepAlive as part of the library.

Any idea why I am seeing this behaviour? Is there any way to catch errors/debug disconnections?

**Comment by numerized** [comment]
I have had the same problem again even after update.
After a while socket are disconnecting.

**Comment by POCO10** [comment]
Any news on this issue? Having the same! :-/

**Comment by subos2008** [comment]
I think it was a red herring. Iirc it was actually my services getting
restarted and nothing to do with this code.

The other library with a similar name seems to be a *lot* more stable than
this one though.
