### ISSUE TITLE
historicalTrades still broken

### ISSUE THREAD

**Issue by marcio1973** [Ashlar/binance-api-node#146]
Historical Trades still broken, when I try call the rest API with this url

https://api.binance.com/api/v1/historicalTrades?symbol=ETHBTC

I receive this error

{"code":-2014,"msg":"API-key format invalid."}

It´s a general endpoint, it´s doesn´t need API-Key

**Comment by ManuCart** [comment]
Hi,
I had this issue. A workout is to send start and end time Params
