### ISSUE TITLE
cancel an unfilled order

### ISSUE THREAD

**Issue by fragender** [Ashlar/binance-api-node#161]
I am asking for help: I work with "binance-api-node". I want to cancel an open order, but this seems to be impossible: canceling requires the orderId. But as long as the order is not filled, there is no orderId available . And when the order is filled, then it is too late for canceling. What am I doing or understanding wrong? How can I cancel a pending (not filled yet) order? How can I get the orderId from an order which is not filled yet? PLease help. 
There seems for me to be a logical contradiction: as long as the order is not filled there is no order ID available for the order. Is this assumption correct? 
If yes: how can I cancel the order without knowing the ID?
If no: how can I get the ID of the order, which I want to cancel? 
Fact is: I do not get the orderId from the order to be canceled.
Can you help me, please?

**Comment by ManuCart** [comment]
Hi,

You can create your own orderid with newClientOrderId.
I use nanoid (https://github.com/ai/nanoid) to create one and save for use later to cancel

**Comment by fragender** [comment]
Hi and thanks, sounds good! But how would I link this orderid with my buy-order?

My question was more aiming at: 
first step is: sending a e.g. buy-order to binance via binance-api-node
2nd step: to make sure the next buy-order doesn't concur with the previous buy-order: cancel all previous buy-orders, if they are still not filled.
3rd step: send the latest buy-order.

For this sequence binance-api-node provides the cancel-tool. This cancel-tool necessitates an order-id. Therefore there must already be an orderId from the non-filled order somewhere deep inside the stomach of binance, I guess. 
But I cannot fish it out from (where?). So how would I retrieve this ID from the non-filled order? Using nanoid (as thankful as I am for your reply!) would only shift my problem to another table.

**Comment by ManuCart** [comment]
If you keep newClientOrderId and symbol in an object, you can send it after with
````binance.cancelOrder({symbol: symbol, origClientOrderId: orderid})````

**Comment by fragender** [comment]
Ah!  :-)
I will check it asap.
This helps double, since I was also wondering how to get "origClientOrderId" from where.
I learn:
I create the origClientOrderId via the above-texted destructuring myself, correct? 
var origClientOrderId = orderId
In other words: Binance does not deliver the origClientOrderId, because Binance does not have it. I have to create it myself.
Correct?

**Comment by fragender** [comment]
Which leads me to another question: What is the difference between orderId and origClientOrderId?
There is an order A (= buy-order) which i sent.
Then there is an order B (=cancel-order), which is supposed to cancel A.
Which is the "order" for orderId and the "original order" for "origClientOrderId"?
Possible conclusion from my side:
orderId and  origClientOrderId are only different parameters but may hold the exact same arguments.
The difference is, how Binance interprets these two parameters.
Would that be right?
Otherwise I cannot imagine the difference between these two notions.

**Comment by ManuCart** [comment]
my script:
````
orderid = nanoid('1234567890ABCDEF', 6)
binance.order({symbol: symbol, newClientOrderId: orderid, side: side, price: price, quantity: quantity}
````
Later...
````
binance.cancelOrder({symbol: symbol, origClientOrderId: orderid})
````

**Comment by fragender** [comment]
Thank you! This is a leap forward for me.

**Comment by dmitriz** [comment]
The option `"newClientOrderId"`does not seem to appear in https://github.com/binance-exchange/binance-official-api-docs

Is it documented anywhere?

**Comment by ManuCart** [comment]
Hi,
Documented at
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade

**Comment by dmitriz** [comment]
Ah yes, thanks a lot!!!

**Comment by balthazar** [comment]
Thanks for the help @ManuCart 🙂
