### ISSUE TITLE
Socket not closing instantly

### ISSUE THREAD

**Issue by salmanfazal01** [Ashlar/binance-api-node#173]
I believe to close a websocket, we just have to call the variable name. In my case, even after I call stop the socket, it runs a couple more times before finally stopping. Something 2-3 times, sometimes even 20 times.

Have a look at my image:

![image](https://user-images.githubusercontent.com/15085416/56171340-e312fa80-5fb2-11e9-812c-f370a40b0b32.png)

After the SL is hit, I call the clean_trade() however, it still did run several more times before finally stopping.

**Comment by balthazar** [comment]
Hum, interesting

**Comment by bralca** [comment]
Any update on this.. I am experiencing the same issue.

**Comment by BusinessDuck** [comment]
@balthazar i have same problem with sockets.

My current configuration.

```javascript
 const unsubscribe = this.api.ws.candles(
            ticker,
            interval,
            this.handlerAdapter(handler, interval),
        );
        return () => {
            unsubscribe({
                delay: 0,
                fastClose: true,
                keepClosed: true,
            });
        };
```

Package ver: 
binance-api-node: 0.10.28
node: 14.16.0

**Comment by balthazar** [comment]
Issue is quite old and we changed socket libraries in the meantime. You shouldn't rely on this behavior and do your own check to avoid any pending socket from being sent.
