### ISSUE TITLE
socket in server not working

### ISSUE THREAD

**Issue by mehrdadphp** [Ashlar/binance-api-node#174]
hi guys

I am using socket in localhost. it worked perfectly.
but when the script was deployed to the server, the socket did not work at all. 
of course, other requests like prices(), ping(), withdrawal() etc. worked out well in server.

is there anyone to help?

**Comment by balthazar** [comment]
Going to need a bit more info on that one

**Comment by mehrdadphp** [comment]
@balthazar I am for need Receive a live price.
a run code : 

```
const clean = client.ws.allTickers(tickers => {
   console.log(tickers)
});
```
but console.log(), not print and not the error.

but the run  method : 
```
client.prices();
```
all prices is recive

**Comment by mehrdadphp** [comment]
How I can see the log connect socket?

**Comment by ManuCart** [comment]
What is the server because on google cloud basics the websocket not work

**Comment by balthazar** [comment]
All the websocket endpoints are tested on Travis and pass. Maybe try using the latest version. Closing.
