### ISSUE TITLE
User websocket not returning anything after a few minutes

### ISSUE THREAD

**Issue by salmanfazal01** [Ashlar/binance-api-node#187]
So basically, if I am running my app (for not sure how long), after sometime the user socket which I first opened doesnt return anything. I've gotta restart my app to restart the socket.

**Comment by salmanfazal01** [comment]
And yes I am using the latest version 0.9.2

**Comment by salmanfazal01** [comment]
Also how do I close the user websocket? If I have this: 

`const clean = client.ws.user(msg => { });`

and I call `clean();` it gives me a `TypeError: clean is not a function.`

**Comment by ManuCart** [comment]
This error came from a non async function

**Comment by POCO10** [comment]
Can you explain further ManuCart? What needs to be done to keep the binance websocket feeds open constantly? Having the same issue.

**Comment by POCO10** [comment]
Any help, tips? My binance websocket streams still disconnect after around 10 to 15 minutes.
I am assuming it is because this package does not send a "pong" every few minutes?

> Web Socket Streams for Binance (2018-11-13)

> General WSS information
> The base endpoint is: wss://stream.binance.com:9443
> Streams can be access either in a single raw stream or a combined stream
> Raw streams are accessed at /ws/<streamName>
> Combined streams are accessed at /stream?streams=<streamName1>/<streamName2>/<streamName3>
> Combined stream events are wrapped as follows: {"stream":"<streamName>","data":<rawPayload>}
> All symbols for streams are lowercase
> A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark
> **The websocket server will send a ping frame every 3 minutes. If the websocket server does not receive a pong frame back from the connection within a 10 minute period, the connection will be disconnected. Unsolicited pong frames are allowed.**

 Much appreciated!

**Comment by or2008** [comment]
have the same issue, in my case the stream is open for like 20 minutes, then disconnect without any error, I have to restart the app to fix this

**Comment by balthazar** [comment]
As per the docs, you need to use

```js
const clean = await client.ws.user(msg => { })
```

As the websocket methods return a promise.

**Comment by jmarrr** [comment]
Hey, I still get this issue using
```
 const clean = await client.ws.futuresAllLiquidations((data) => { });
 ```
 
 Any suggestion?
