### ISSUE TITLE
bundling failed: Error: Unable to resolve module `crypto`

### ISSUE THREAD

**Issue by samcampisi** [Ashlar/binance-api-node#189]
I'm trying to add binance-api-node to my react native app and I can't get it to work.

All I'm getting is this error

<img width="452" alt="Screenshot 2019-07-04 at 13 53 11" src="https://user-images.githubusercontent.com/42766924/60664807-1bfc9600-9e63-11e9-8a49-39cfe538e293.png">

Is there something I'm missing to get this up and running? I tried everything on the readme.

Node Version: 8
npm version: 6.4.1
React Native version: 0.60.0
binance-api-node version: 0.9.2

**Comment by balthazar** [comment]
Google is your friend, issue out of scope.

**Comment by samcampisi** [comment]
In case anyone is looking for a helpful solution, I am using [binance-api-react-native](https://github.com/gkoychev/binance-api-react-native) since react native and 'crypto', 'stream' and the like don't work well together without altering your .babelrc or using nodefy.

**Comment by balthazar** [comment]
For people who don't want to use a completely outdated package, you should look into https://github.com/petejkim/node-libs-react-native to polyfill node libs for react native, which is a less hacky way to go about things.
