### ISSUE TITLE
Question about user websocket

### ISSUE THREAD

**Issue by ManuCart** [Ashlar/binance-api-node#190]
Hi,
I use same code for 2 differents bots working on 2 differents machines but  in same sub-network.
When I close the user websocket on the first bot, the second bot not receive anymore information from websocket user.
Really strange.
Have you ever heard about this?

**Comment by balthazar** [comment]
No I did not, but it is probably the way the binance api handles close events by terminating all active connections. Maybe you should have a channel between your bots in order to notify the close and reopen a new connection.
