### ISSUE TITLE
await client.accountInfo() bug

### ISSUE THREAD

**Issue by LowArmour** [Ashlar/binance-api-node#191]
When using await client.accountInfo(), I get the following error:

```js
(node:14652) UnhandledPromiseRejectionWarning: TypeError: getTime is not a function
    at /****/****/*****/node_modules/binance-api-node/dist/http-client.js:161:26

line 161 is:
    }) : Promise.resolve(getTime())).then(function (timestamp) {
```

Which is right, when consoled log getTime, it is the time in ms, not a function. I think it should be getTime and not getTime()?

Many thanks,

**Comment by ManuCart** [comment]
No problem for me, try my code
````
const Binance     = require('binance-api-node').default
const binance     = Binance({apiKey: config.binance.key, apiSecret: config.binance.secret})
let account = await binance.accountInfo()
console.log(util.inspect(account, false, null, true ))
````

**Comment by balthazar** [comment]
Likely an issue on how you use the lib on your side. Are you providing  custom `getTime` function? If so you should try to remove it :)

**Comment by ASHKARAN** [comment]
you can use this code to get an instance of binance client
const Binance     = require('binance-api-node').default
const client =    Binance({
                apiKey: process.env.binanceAPIKey,
                apiSecret: process.env.binanceSecretKey ,
                getTime:  () => Date.now()
            })
