### ISSUE TITLE
Error: Order does not exist. Code - 2013

### ISSUE THREAD

**Issue by rahuldamodar94** [Ashlar/binance-api-node#196]
The order placed was successful and I also received the orderId from the response. But when I pass this orderId to the getOrder method, I get the error: Order does not exist. How can an orderId returned by binance give a does not exist error ? 

Thank you in advance.

**Comment by balthazar** [comment]
Not sure honestly, maybe they had an issue and had to delete some orders? Can't tell as I do not work for Binance, try to contact them about it rather. Closing
