### ISSUE TITLE
TypeError: httpMethods is not a function

### ISSUE THREAD

**Issue by omega1119** [Ashlar/binance-api-node#202]
Hi there,

I got latest of 0.9.7 via npm and when I run

```
const clean = await client.ws.user(msg => {
  ...
})
```

I get the following error:

(node:2667) UnhandledPromiseRejectionWarning: TypeError: httpMethods is not a function
    at Object.user (/../node_modules/binance-api-node/dist/websocket.js:338:23)

Any help would be much appreciated.

Thanks

**Comment by balthazar** [comment]
Should be good in the latest release `0.9.8`, sorry about that

**Comment by omega1119** [comment]
Thanks,

but I have another one unfortunately.

(node:2326) UnhandledPromiseRejectionWarning: Error: Not a margin account.
    at /../node_modules/binance-api-node/dist/http-client.js:55:17

**Comment by balthazar** [comment]
Seems like this one is because your binance account doesn't have margin trading enabled

**Comment by omega1119** [comment]
Thanks, that fixed the error. You may want to document it as a prerequisite or make it optional to have a margin trading account.

**Comment by balthazar** [comment]
You did not pass the margin param?

**Comment by omega1119** [comment]
`user(callback: (msg: OutboundAccountInfo | ExecutionReport) => void): Function`

I didn't see any options for a margin parameter.

**Comment by omega1119** [comment]
Also, I can't see this method either:

`client.ws.marginUser()`

**Comment by balthazar** [comment]
The release `0.9.9` should have fixed the issue, you don't need a margin account anymore.

**Comment by omega1119** [comment]
Thanks, is it possible to disable the margin trading account? I can't see anything immediately in the UI.

**Comment by balthazar** [comment]
Not familiar with that, ask Binance support

**Comment by omega1119** [comment]
Will do, in which case I can't test the latest update at the moment, but I will assume it works :)
