### ISSUE TITLE
Make endpoint as a parameter in constructor

### ISSUE THREAD

**Issue by YoleYu** [Ashlar/binance-api-node#206]
The default endpoint is 'https://api.binance.com',
But some area can't access this url, instead of https://www.binancezh.com

So make the endpoint as an optional param is reasonable.

**Comment by balthazar** [comment]
I believe #205 should have fixed this issue by allowing to provide an `endpoints.base` in the options [here](https://github.com/Ashlar/binance-api-node/commit/44748d4252e4bc34bce15421e18bf3e23d5a8967#diff-ab4b11a4a0f024bbfafeda47a386d545R221).

Let me draft a new release including this and let me know how it goes.

**Comment by balthazar** [comment]
`0.9.10`

**Comment by DealSegfault** [comment]
```js
const domain = {
    production: "api.binance.com",
    testnet: "testnet.binancefuture.com"
 }
```

Currently

```ts
export default function(options?: {
    apiKey: string
    apiSecret: string
    getTime?: () => number | Promise<number>
  }): Binance
```

How it should be
 
```ts
export default function(options?: {
    apiKey: string
    apiSecret: string
    httpBase: string
    httpFuture: string
    getTime?: () => number | Promise<number>
  }): Binance
```

You can add the field httpBase

```js
const client = Binance({
    apiKey: 'xxx',
    apiSecret: 'xxx',   
    httpBase: domain.testnet
})

```

**Comment by hp8wvvvgnj6asjm7** [comment]
https://github.com/Ashlar/binance-api-node/issues/280
