### ISSUE TITLE
Deprecated Endpoint

### ISSUE THREAD

**Issue by bralca** [Ashlar/binance-api-node#208]
Hi, I am not receiving data anymore from the client for some methods, including "Candles". 

I think it might have to do with a recent system upgrade from Binance --> https://binance-docs.github.io/apidocs/spot/en/#change-log 

Anybody with the same issue?

**Comment by balthazar** [comment]
Possible yes, but aren't the endpoints supposed to be out in Q1 2020?

**Comment by bralca** [comment]
Yes, you are right. They will be out in 2020. What is going to happen to this client then?

**Comment by balthazar** [comment]
The update is pretty straightforward, so not sure what you mean 😄 You could even make a pr today
