### ISSUE TITLE
Found 54 vulnerabilities

### ISSUE THREAD

**Issue by bennyn** [Ashlar/binance-api-node#211]
Running `npm install` on this project finds 54 vulnerabilities (2 low, 1 moderate, 50 high, 1 critical). There is also no `package-lock.json` file.

Given the nature of this library (trading crypto assets which have high value) it should not have any severe vulnerability. Let's do a `npm audit` to fix this. 💪 

**Report:**

![image](https://user-images.githubusercontent.com/469989/69100013-843bc500-0a5c-11ea-8d95-885356f9a214.png)

**Comment by balthazar** [comment]
This is irrelevant as they are all dev dependencies

**Comment by bennyn** [comment]
Good to hear but at the first glance it seems frightening. What stands against an update of the dev dependencies?

**Comment by balthazar** [comment]
Nothing much, but you made it sound like there would be potential security vulnerabilities in using this lib, so just wanted to clarify. Open to bump them of course, but you'll notice than even if you upgrade all of them, some "vulnerabilities issues" will always remain because of sub-dependencies.
