### ISSUE TITLE
Futures Support?

### ISSUE THREAD

**Issue by hunsoo** [Ashlar/binance-api-node#220]
From what I see on http-client.js, there are some methods to access futures data streams.

I would like to know if futures support for REST/websocket is already there but undocumented, or a work in progress.

**Comment by aneopsy** [comment]
+1

**Comment by hunsoo** [comment]
I have been waiting for a bit sitting on this one, hoping someone could enlighten me. But no luck so far... So I might just share how far I digged it myself just in case anyone is interested.
It does have some workarounds for the futures REST calls by making unmanaged calls with publicRequest/privateRequest, as mentioned in #205 ... so I can do futures REST calls like this, though not too ideal.
ex)
`const futuresAccountInfo = await client.privateRequest('GET', '/fapi/v1/account')
`
It would be nice to have everything organized by the type of account (spot/margin/futures) you are dealing with.
ex) 
`const spotAccountInfo = await client.spot.accountInfo()
const marginAccountInfo = await client.margin.accountInfo()
const futuresAccountInfo = await client.futures.accountInfo()
`

For Websockets, there are a few things to be addressed to make it work. I don't think it is possible to make it work with futures stream without modifying the source code.
1. Futures base endpoint is different : Instead of stream.binance.com, we need fstream.binance.com
2. Listen key manangement for the futures stream: These are already in http-client.js 
3. The format of account info/trade info websockets messages are different from spot/margin

I believe 1 and 2 can be handled without too much modification on the source code.
3 is just a bit of extra work on userTransforms mapping. instead of outboundAccountInfo event, now we have ACCOUNT_UPDATE, and instead of executionReport, we have ORDER_TRADE_UPDATE. The structure of each object is a tad bit different too.

I am still having some trouble with 2 though... I keep getting a new listenkey only for the futures stream every 30 seconds and not sure why. spot/margin streams keep the current listen key without any problem.

I can only see that from the documentations, spot/margin uses {listenkey} as param, but futures uses {timestamp, recvWindow} as param. Perhaps this might be related?

https://binance-docs.github.io/apidocs/spot/en/#user-data-streams
https://binance-docs.github.io/apidocs/futures/en/#user-data-streams

At this point, I am a bit lost and might just use polling with REST as a temporary solution. Hope I could figure out this one soon enough.

**Comment by hunsoo** [comment]
After a good amount of tracking things down, at least I was able to keep a constant listenkey for the futures stream, which means I can access the messages from the stream now.

So it happened because some malformed request receives invalid JSON response (Passthrough object?) and the code tries to parse it then got an error, then tried to close the stream immediately. I just put a few band-aid error handlings a bit just to make it work, but it still spits out some unhandled promise rejection errors... I guess I can live with it for now.

**Comment by aneopsy** [comment]
PR available #225

**Comment by balthazar** [comment]
Closing as it's now available thanks to @aneopsy

**Comment by AlberErre** [comment]
As @hunsoo pointed out, `fstream.binance.com` is not being used on `src/websocket.js`. 
Any plans to implement this? 🚀

**Comment by hunsoo** [comment]
@AlberErre I worked on partial futures websocket support for my own use in January. As it does not have complete support yet (it only has access to mark price, account info and order update feed), I have not made a PR for this yet. Once my job eases me up a little more, I will finish it up and make a PR.

**Comment by joshstevens19** [comment]
Any news on fstream.binance.com would be awesome if you could share your own support @hunsoo, polling using rest is a temp but not a complete solution.
