### ISSUE TITLE
Price * QTY is zero or less

### ISSUE THREAD

**Issue by lcpsd** [Ashlar/binance-api-node#223]
hi! how i can resolve the error "Price * QTY is zero or less"?, i dont understand why this error because if i multiply my price param and my quantity the result is most bigger that 1 ..

**Comment by balthazar** [comment]
Afraid this repo is only a library around the api and there's not much additional insight I can provide. I would advice to contact the api folks directly on TG @binance_api_english

**Comment by lcpsd** [comment]
i contact the support, and it's solved changing the number of decimals in my order , thanks ! :D
