### ISSUE TITLE
Add URL to errors in case of API call rejection

### ISSUE THREAD

**Issue by bennyn** [Ashlar/binance-api-node#227]
I reached the point where I have made more API calls to Binance than I should and therefor received a temporary ban with error code `-1003` (TOO_MANY_REQUESTS):

> Error: Way too much request weight used; IP banned until 1579697607710. Please use the websocket for live updates to avoid bans.
    at node_modules\binance-api-node\dist\http-client.js:59:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: -1003
}

In such cases it would be nice to know which API call failed so that I can find out which endpoint I queried too often. Unfortunately "binance-api-node" does not add this information. 

How about adding the requested URL as property or text to the `Error` object which [is constructed here](https://github.com/Ashlar/binance-api-node/blob/0.9.11/src/http-client.js#L39)?

**Comment by balthazar** [comment]
Wouldn't it just add the url of the last queried call that fails rather than the one being queried too much, which could be different?

**Comment by bennyn** [comment]
No. In my test `res.url` returned https://api.binance.com/api/v1/exchangeInfo which was also the resource I queried too often.

**Comment by balthazar** [comment]
Then yeah that sounds good

**Comment by bennyn** [comment]
Ok, I will prepare a PR. 🌞

**Comment by bennyn** [comment]
Thanks for [merging it](https://github.com/Ashlar/binance-api-node/pull/228) but it looks like the tests fail now:

> auth › [REST] depositHistory

**Comment by balthazar** [comment]
Yeah I know, looking at that
