### ISSUE TITLE
Multiple Intervals

### ISSUE THREAD

**Issue by jkr137** [Ashlar/binance-api-node#232]
Binance websocket api allows multiple intervals to receive candlestick live data, it will be nice if binance-api-node adds this. Instead of one interval it can be array of İntervals.

here is a simple test:

https://jsbin.com/depedoziqa/edit?html,output

**Comment by balthazar** [comment]
It does allow it

**Comment by jkr137** [comment]
hello, am i missing something? It doesn't work this way. Thank you so much.

binance.ws.candles(arrayofsymbols, ['1m','5m','15m'], candle => {
    console.log(candle)
});

**Comment by jkr137** [comment]
hello, am i missing something? It doesn't work this way. Thank you so much.

binance.ws.candles(arrayofsymbols, ['1m','5m','15m'], candle => {
    console.log(candle)
});
