### ISSUE TITLE
Rate Limits?

### ISSUE THREAD

**Issue by DakotaLarson** [Ashlar/binance-api-node#238]
Hi,
First off, this is the repo for this: https://www.npmjs.com/package/binance-api-node package right?

The Binance API has limits: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#ip-limits and I was wondering if there are plans to integrate these response headers into the parsed responses from this library. Thoughts on this?

Thanks!

**Comment by balthazar** [comment]
Hey, yes that's it, you can check in the `package.json` for that

The error should be surfaced directly and can be catched since we are using promises 🙂
