### ISSUE TITLE
Please add Dustlog

### ISSUE THREAD

**Issue by paulkoanui** [Ashlar/binance-api-node#245]
Thanks for a great library.  I'm interested in being able to net out all transactions manually so that I can arrive at a portfolio state that matches what is reported by Binance.  The only part that is missing from being able to do that with this library is to support retrieving the Dust log.

See: https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#dustlog-user_data

I can submit a PR for this if you're accepting them...

Cheers!

**Comment by balthazar** [comment]
Yes of course we accept PRs :)
