### ISSUE TITLE
Switch to TypeScript?

### ISSUE THREAD

**Issue by lookfirst** [Ashlar/binance-api-node#249]
After submitting one PR for fixing the type definitions and getting it merged, thanks, I have to ask... why not just use TypeScript for this project? It removes the need to maintain that types file entirely and you get all the benefits of TypeScript.

**Comment by balthazar** [comment]
Not a TypeScript fan, I don't mind having type definitions that people who use it maintain, but I don't want to bother too much about it :smile:

**Comment by lookfirst** [comment]
That's too bad.
