### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lookfirst** [Ashlar/binance-api-node#250]
What is the license for this project?

**Comment by balthazar** [comment]
https://github.com/Ashlar/binance-api-node/blob/master/package.json#L55

**Comment by lookfirst** [comment]
I'm sorry, but that is not enough. You really should place a LICENSE.txt file at the top level as well as declaring the copyright ownership of the code.

https://choosealicense.com/licenses/mit/

![image](https://user-images.githubusercontent.com/85355/80873360-cc4a4f00-8c6c-11ea-9ae4-754405deae1d.png)

**Comment by lookfirst** [comment]
I also suggest that you setup a CLA tracking service.

**Comment by lookfirst** [comment]
Also, rtfm. https://choosealicense.com/no-permission/

**Comment by lookfirst** [comment]
Also: https://opensource.stackexchange.com/questions/5484/how-to-use-mit-license-in-a-project

**Comment by balthazar** [comment]
lmao, asking me to rtfm on my own repo when you didn't take the slightest time to check the package or the npm [page](https://www.npmjs.com/package/binance-api-node) which clearly displays the license, which is what most people install and thus require. Quite the ironic statement!

I can sense you took offense by something, but you're welcome to make a PR and add a license file to satisfy your demand.

About a CLA -> :rofl: What's next, a code of conduct? :santa: 

There's also a cool feature that was developed recently, the key "Enter" on your keyboard, allowing you to create newlines in your comment without having to spam my inbox with your single lines replies, try it, it works!

**Comment by lookfirst** [comment]
You complain about a one line response after giving me a one line response.

![image](https://user-images.githubusercontent.com/85355/80890729-0e2ac380-8c74-11ea-9270-f2c16d95fa9d.png)

**Comment by balthazar** [comment]
Is that you facepalming at your own imbecility? Don't worry you're not the only one!

Before replying, try to think a little more about your argumentation, or the appropriate meme to use if you lack reasoning (and originality). Although honestly I think it's time for you to step away from the keyboard, you're just making a fool of yourself.
