### ISSUE TITLE
How to use with new mjs module

### ISSUE THREAD

**Issue by emmtte** [Ashlar/binance-api-node#251]
tried for new mjs module with nodejs 14: 
````
import Binance from 'binance-api-node'
const binance = Binance()
````
have this error
````
const binance = Binance({
                ^

TypeError: Binance is not a function
````

**Comment by maxdumas** [comment]
This is because the default export for this package isn't exported in a way that is compatible with ESM default imports. The correct way to import this package in an ESM environment is the following:

```ts
import { default as Binance } from "binance-api-node";

const client = Binance();
```

**Comment by SrBrahma** [comment]
> This is because the default export for this package isn't exported in a way that is compatible with ESM default imports. The correct way to import this package in an ESM environment is the following:
> 
> ```ts
> import { default as Binance } from "binance-api-node";
> 
> const client = Binance();
> ```

This doesn't fix the issue for me. The error still happens :/
