### ISSUE TITLE
Add support for allOrderList (Query all OCO )

### ISSUE THREAD

**Issue by Amantel** [Ashlar/binance-api-node#252]
Hi! 
There is an API endpoint https://binance-docs.github.io/apidocs/spot/en/#query-all-oco-user_data which is not a part of this repo. 
Can add it?  Do you need a pull request for that? 
Thanks.

**Comment by balthazar** [comment]
Hey :)

Yes, a PR with tests would be appreciated

**Comment by Amantel** [comment]
My testing account seems to have no OCO, but the gist of it is just coping allOrders and sending there mandatory timestamp. Will do PR ASAP
