### ISSUE TITLE
How to set order quantity to "100%" like in the app?

### ISSUE THREAD

**Issue by nstranquist** [Ashlar/binance-api-node#265]
Hello, thank you for your work.
I would like to buy/sell 100% of the balance in a market order. Would there be a way for me to do this with the required "quantity" field in the order, or is there a way to get the current balance and calculate it that way?

Thank you.

**Comment by nstranquist** [comment]
Okay, I am seeing now that the "quantity" field of a market order is optional. Perhaps excluding this will give me the 100% quantity I am seeking.

**Comment by iterums** [comment]
When you place a market order, either `quantity` or  `quoteOrderQty` are mandatory. See https://binance-docs.github.io/apidocs/spot/en/#new-order-trade

You can get your account balance(s) with https://github.com/Ashlar/binance-api-node#accountinfo

**Comment by nstranquist** [comment]
Thanks!
