### ISSUE TITLE
Project status w.r.t. release tags and npm listing

### ISSUE THREAD

**Issue by jorisw** [Ashlar/binance-api-node#273]
Hi,

The [seemingly official repository](https://github.com/binance-exchange/binance-api-node) is a fork of this one.

Neither repositories' release tags on GitHub accurately mirror the version [listed in npm](https://www.npmjs.com/package/binance-api-node).

This repo seems one patch version ahead of the official one, judging from the [`package.json`](https://github.com/Ashlar/binance-api-node/commit/6a827c574376f4551c6f9e9315fa8680e515ed83), however the latest GitHub release tag on this repo is years behind.

Which of these repos is represented at npm?

Why isn't a GitHub repo listed at npm? It would help prevent confusion with [unofficial repos](https://github.com/jaggedsoft/node-binance-api).

**Comment by balthazar** [comment]
This is the official repo, the fork is simply the way binance had to centralize all of the libraries in one place

You're calling a fork the official repo, which doesn't really make sense :) You can view the fork on the binance org as the proof this repo is actually the official one

I don't push releases on GitHub and don't update the fork often. It is true however that the homepage could be listed in the package

**Comment by jorisw** [comment]
Thanks for adding the homepage to the package.

I still think the fork, carrying Binance's name, is very confusing. It would make most sense if the official package carried Binance's name and was the primary repo. To me, making forks is the worst possible way to 'collect' things in place. It really makes it look like binance-exchange/binance-api-node is the officia repo that was for some reason forked off of an unoffiial one.

binance-exchange/binance-api-node is also much behind this repo now. Its versions are not maintained at all, its latest release is from 2018. I would strongly suggest both repos refer to eachother to clear up why both exist, and which one to refer to for day to day use.

**Comment by balthazar** [comment]
I do not have admin access to the fork and cannot disable the releases tab, it was not my decision to do it this way and I don't really agree with it for the record 🙂
