### ISSUE TITLE
.futuresUser() method doesnt work...

### ISSUE THREAD

**Issue by anwebdevelopers** [Ashlar/binance-api-node#282]
It should process and give such data as in the screenshots or by links [1](https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update) [2](https://binance-docs.github.io/apidocs/futures/en/#event-order-update), but it is not provided in your code ... This is only the first function in your library that I tried to use for the futures market. Hopefully this is just one non-working feature, and I look forward to a fix. Thanks
![image](https://user-images.githubusercontent.com/26022868/97438451-40289400-193e-11eb-8a13-12234daca727.png)
![image](https://user-images.githubusercontent.com/26022868/97438492-4b7bbf80-193e-11eb-845e-439f109d7788.png)

**Comment by aldomalerba** [comment]
Hi @anwebdevelopers 
Have you try to check if you have enabled the Futures Account on Binanace ?

To enable futures rest api and ws you have to create future account and after you have to create an API  Key with at least this restrictions:
<img width="847" alt="Schermata 2020-11-23 alle 22 16 21" src="https://user-images.githubusercontent.com/26540470/100016515-d46d0600-2dd9-11eb-8417-c904daaa2adb.png">

**Comment by anwebdevelopers** [comment]
> Hi @anwebdevelopers
> Have you try to check if you have enabled the Futures Account on Binanace ?
> 
> To enable futures rest api and ws you have to create future account and after you have to create an API Key with at least this restrictions:
> <img alt="Schermata 2020-11-23 alle 22 16 21" width="847" src="https://user-images.githubusercontent.com/26540470/100016515-d46d0600-2dd9-11eb-8417-c904daaa2adb.png">

HI @aldomalerba 
And here is it? Naturally, I created a new API key with the necessary permissions ... I understand why I am writing, I have been developing software for trading through the API for several years. You will look at the code of this library and you will see that it does not provide for data processing as in my screenshots and links above. If you are not aware, then the API of the spot market and the API of the futures market are very different in many ways.

**Comment by aldomalerba** [comment]
Hi @anwebdevelopers ,
I'm sorry, I did not understended the issue, now it is clear.
I understood that the method did not return any data, instead the problem is that the data returned  are not the same as the api documentation in the screenshots, right?
I'm sorry for the misunderstanding.

**Comment by anwebdevelopers** [comment]
Почти верно. Метод потается обработать данны как на спотовом АПИ, но так как данные приходят в другом виде - он не возвращает ничего.

> Hi @anwebdevelopers ,
> I'm sorry, I did not understended the issue, now it is clear.
> I understood that the method did not return any data, instead the problem is that the data returned are not the same as the api documentation in the screenshots, right?
> I'm sorry for the misunderstanding.

Almost true. The method tries to process the data as on a spot API, but since the data comes in a different form, it does not return anything.
![image](https://user-images.githubusercontent.com/26022868/100223761-5aea2a80-2f35-11eb-95b2-0c7967397908.png)
