### ISSUE TITLE
prices with symbol fails: r.reduce is not a function

### ISSUE THREAD

**Issue by gelito** [Ashlar/binance-api-node#287]
If you launch prices with a symbol 

```
const price = await client.prices({
  symbol: 'ETHBTC'
});
```

fails, and receives an error:  `r.reduce is not a function`

Reading the code looks like the method wait for an array and receives only an object.

Works well when you do it without symbols.

"binance-api-node": "0.10.11",
node: v14.14.0

**Comment by balthazar** [comment]
Seems like the issue comes from your code, not the library

**Comment by gelito** [comment]
Sorry, but it's just because the Binance API can return an Object or Array. 
https://binance-docs.github.io/apidocs/spot/en/#symbol-price-ticker

But the library has an r.reduce and don't check it:
https://github.com/Ashlar/binance-api-node/blob/92b908a85994a9544e6a1b5045c1ec56ef8074df/src/http-client.js#L266

**Comment by balthazar** [comment]
Your issue title mentioned a reducer, thus my original answer :slightly_smiling_face: 
It must be something they changed, as it was previously working

**Comment by gelito** [comment]
Fixed the title ;-) 

The same problem could happen in other endpoints, but it's easy to fix.
