### ISSUE TITLE
Have an option to init client with TestNet endpoints

### ISSUE THREAD

**Issue by purehtc** [Ashlar/binance-api-node#297]
It would be nice to have an option when initializing the client to set the API to the TestNet endpoints instead of the production API.

// Authenticated client, can make signed calls
const client2 = Binance({
  apiKey: 'xxx',
  apiSecret: 'xxx',
  getTime: xxx, 
  apiEndpoints: 'TestNet' // defaults to 'production'
})

**Comment by itman85** [comment]
any update on this issue? testnet api is needed for new player as me

**Comment by jorisw** [comment]
Would be fixed by #278 and/or #283

**Comment by balthazar** [comment]
Available since 0.10.26
