### ISSUE TITLE
[FEATURE] allOrders for FUTURES

### ISSUE THREAD

**Issue by dawadam** [Ashlar/binance-api-node#300]
Hi,
All orders function is great, but we can't use it with futures api url.

```
    allOrders: function allOrders(payload) {
      return privCall('/api/v3/allOrders', payload);
    },
```

It will be good to have futures version like this :

```
    futuresAllOrders: function futuresAllOrders(payload) {
      return privCall('/fapi/v1/allOrders', payload);
    },
```

**Comment by yanaice** [comment]
:'(

**Comment by yanaice** [comment]
:'(

**Comment by yanaice** [comment]
function **futuresAllOrders** has been added in **_http-client.js,_** but hasn't been added in _**index.d.ts**_ file (><")

**Comment by balthazar** [comment]
@yanaice Feel free to make a PR for it, I will gladly merge that in 🙂
