### ISSUE TITLE
New Order 

### ISSUE THREAD

**Issue by ManuelJH76** [Ashlar/binance-api-node#306]
Hello
I followed the code from the example:
var result = client.Spot.Order.PlaceOrder(SelectedSymbol.Symbol, OrderSide.Buy, OrderType.Limit, SelectedSymbol.TradeAmount, price: SelectedSymbol.TradePrice, timeInForce: TimeInForce.GoodTillCancel);

No matter what change I make, there are a number of error messages. I can't quite understand this, I'm trying to execute various short with the order, for example: SelectedSymbol.TradeAmount = 0.00200000M.

For courses, for example. Price: 0.00000023 I get the error Price * QTY is zero or less. 
For courses, for example. Price: 0.00002468 comes the message LOT_SIZE. 

If I trigger the order directly via Binance, it will be placed.

Thank you for your support.

**Comment by balthazar** [comment]
The error message is pretty obvious: you're just giving bad params for the symbol you're giving, probably the protection they have for fat fingering among other things

**Comment by ManuelJH76** [comment]
Hi there,
I update the symbol data shortly before the order and have compared it with the life data and these match. If you talk about bad parameters it would be great if you could say what you mean by that ...

Thanks for your support.
