### ISSUE TITLE
NewOrder `quantity` type Issue

### ISSUE THREAD

**Issue by oknoorap** [Ashlar/binance-api-node#313]
I just found issue about quantity type (but maybe not an issue) in `index.d.ts`, is it true that quantity is string? I think it should be number, am I right?

```typescript
export interface NewOrder {
    icebergQty?: string
    newClientOrderId?: string
    price?: string
    quantity: string // <<<<<<< this should be a number
    recvWindow?: number
    side: OrderSide
    stopPrice?: string
    symbol: string
    timeInForce?: TimeInForce
    useServerTime?: boolean
    type: OrderType
    newOrderRespType?: NewOrderRespType
    isIsolated?: boolean
    quoteOrderQty?: string
    sideEffectType?: SideEffectType
  }
```

**Comment by balthazar** [comment]
@bennycode

**Comment by bennycode** [comment]
@oknoorap, the quantity is of type decimal and because JavaScript's `number` type is not precise enough for floating point numbers, it has to be sent as `string`. You can find more info about it here: https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#new-order--trade

**Comment by oknoorap** [comment]
okay, so is it valid when I send order with quantity value type string?

```javascript
// From read me
console.log(
  await client.order({
    symbol: 'XLMETH',
    side: 'BUY',
    quantity: 100,
    price: 0.0002,
  }),
)

// Is this code valid and will be executed?
console.log(
  await client.order({
    symbol: 'TRXUSDT',
    side: 'BUY',
    quantity: '100.1',
    price: 0.0002,
  }),
)
```

**Comment by bennycode** [comment]
@oknoorap Yes, that is correct.

@balthazar I updated the docs to reflect this behaviour: https://github.com/Ashlar/binance-api-node/pull/314

**Comment by balthazar** [comment]
Cool thanks benny, closing

**Comment by oknoorap** [comment]
cool thanks @bennycode and @balthazar
