### ISSUE TITLE
"Timestamp for this request is outside of the recvWindow"

### ISSUE THREAD

**Issue by Parth2404** [Ashlar/binance-api-node#315]
Hi,

I am using this module for making a request to Binance but for some reason, the server starts returning an error after some successful execution of API.

I have asked question on StackOverflow and it contains more details about it, here is the link: https://stackoverflow.com/questions/65750326/nodejs-binance-api-timestamp-for-this-request-is-outside-of-the-recvwindow

**Comment by balthazar** [comment]
Are you sure your computer clock isn't shifting over-time which would explain the error? Try to time the requests, could be another possibility

**Comment by Parth2404** [comment]
Hi @balthazar, I checked for any possible timeshift but there was none, there was a difference of 150 to 200 ms in server time and local time but I synced it by subtracting the difference from local time.

I am logging the timestamp when I am receiving the request and the time the request was made I observed that the time difference between receiving the response and the time which request was made is gradually increasing, that is not how it should behave.

You would get a better idea if you run the code that is given in the stackoverflow question.

**Comment by balthazar** [comment]
Your code doesn't even wait for the completion of the first request to fire up another one, doesn't surprise me that it eventually timeouts

**Comment by Parth2404** [comment]
You are saying that the issue is with how the code is written?? 

There is no need to wait as it is a promise. Please elaborate if i am missing the point here.

**Comment by Parth2404** [comment]
Hi, @balthazar what can be done to solve this issue??

**Comment by krolov** [comment]
The easiest way - to increase recvWindow, most of the requests contain it.
Also, you can try to send requests to different endpoints. It could increase receive/response time.
If your latency to the Binance server is low you can wait for the response from the previous request and then send a new one.
