### ISSUE TITLE
Market buy order response

### ISSUE THREAD

**Issue by defaultbeep** [Ashlar/binance-api-node#321]
Hi,

I'm interest in making a MARKET buy order via the API and I'm wondering if its safe to assume the response would be details of a FILLED order? I'm not 100% sure myself.. I've tested it a little and its been FILLED every time but I have my concerns the status  could be new or partially filled if theres not enough sellers to fill the order... that is unless Binance don't send a response until the orders filled.

**Comment by krolov** [comment]
The market order does not have a guaranty to be filled. Sometimes it filled after few moments when you get a response, so you'll receive PARTIALLY_FILLED or NEW.

**Comment by defaultbeep** [comment]
Thanks @krolov. I found that in most cases the order was filled immediately but good to know what to expect when it isnt
