### ISSUE TITLE
Add types for all futures streaming APIs

### ISSUE THREAD

**Issue by evgenyfedorenko** [Ashlar/binance-api-node#324]
Hi. Can we add types for futuresDepth and the rest?
If needed I can create a PR.

Thanks.

**Comment by balthazar** [comment]
Hey, a PR would be appreciated indeed! Thanks!

**Comment by evgenyfedorenko** [comment]
added a PR https://github.com/Ashlar/binance-api-node/pull/326

**Comment by evgenyfedorenko** [comment]
merged
