### ISSUE TITLE
Typo in naming

### ISSUE THREAD

**Issue by krolov** [Ashlar/binance-api-node#329]
Hi @balthazar. I Found some typo in property naming. In types I named this property "usedWeight1m", but in legacy code, this name is "usedWeigh1m"

```
const headersMapping = {
  'x-mbx-used-weight-1m': 'usedWeigh1m',
```

What to do in this case? Update types or code? I afraid to ruin somebody back compatibility

**Comment by balthazar** [comment]
They were recently added, so it should be fine to update it to the non-typo version
