### ISSUE TITLE
Missing types for futures WS api

### ISSUE THREAD

**Issue by lucas-labs** [Ashlar/binance-api-node#331]
I noticed that most of the methods of the futures WS api are missing types definition:

- `futuresCandles`
- `futuresAggTrades`
- `futuresAllTickers`
- `futuresTicker`

Also, the method `client.ws.futuresUser` is defined to return `OutboundAccountInfo | ExecutionReport`, which is incorrect. The user WS for futures returns 3 different types of objects.

I might be able to send a PR in the next week if you guys think its ok.

Cheers!

**Comment by balthazar** [comment]
PRs always welcome!

**Comment by phl3x0r** [comment]
Addressed the `ACCOUNT_UPDATE `type on `client.ws.futuresUser` here:
https://github.com/Ashlar/binance-api-node/pull/345

**Comment by phl3x0r** [comment]
Added more missing types here: https://github.com/Ashlar/binance-api-node/pull/354

**Comment by klemensz** [comment]
I added `client.ws.futuresAggTrades` and changed from `Trade` to `AggregatedTrade` - see PR.

**Comment by yovanoc** [comment]
always missing futuresCandles
