### ISSUE TITLE
Support for single SymbolInfo

### ISSUE THREAD

**Issue by subtl3ty7** [Ashlar/binance-api-node#338]
Hello, I currently do not see any way to retrieve information of only one symbol. ( I need that to get tickSize and stepSize for a certain symbol). It seems it is only possible right now by calling exchangeinfo() and it fetches over 1000 symbol info. I am sure Binance provides an endpoint to retrieve a single symbol info. Are there any plans on adding it?

**Comment by krolov** [comment]
Binance does not provide an endpoint to retrieve a single symbol info

**Comment by ltyu** [comment]
> Binance does not provide an endpoint to retrieve a single symbol info

Hello, I know this is closed but binance does allow you to retrieve a single symbol via the parameter `symbol` e.g. `/api/v3/exchangeInfo?symbol=BTCUSDT`. It even specifies in the GitHub docs page

"Get the current exchange trading rules and symbol information. You can optionally pass a symbol to only retrieve info of this specific one." 

Seems to be missing?
