### ISSUE TITLE
httpbase and wsbase don't work with Binance testnet

### ISSUE THREAD

**Issue by petegregoryy** [Ashlar/binance-api-node#344]
setting the httpBase and wsBase to the testnet addresses returns 404, am I just doing this wrong or does this API not support the testnet?

`const client = Binance(
    {
        apiKey: "[testnetKey]",
        apiSecret: "[testnetSecret]",
        httpBase: 'https://testnet.binance.vision/api',
        wsBase: 'wss://testnet.binance.vision/ws',
        useServerTime: true
    }
);`
just returns
`(node:6364) UnhandledPromiseRejectionWarning: Error: 404 Not Found <html><body><h2>404 Not found</h2></body></html>`

**Comment by vyobukhov** [comment]
Options should be specified like this (httpBase doesn't need `/api`):
```
{
    httpBase: 'https://testnet.binance.vision',
    wsBase: 'wss://testnet.binance.vision/ws'
}
```

**Comment by balthazar** [comment]
Thanks @vyobukhov 😃
