### ISSUE TITLE
How to limit the banned error

### ISSUE THREAD

**Issue by Bamorem** [Ashlar/binance-api-node#346]
Hi guys,

I recently get some IP banned, but until now i never got this and i didn't change anything on my code.

Anyway I manage multiple users (binance account) via my script and what i need to do is :

- Get the comission for an order. (Weight: 5)
To do so, the only solution that i found is to request the myTrades().
- get the order details with getOrder (Weight: 1)
- check the user Balances accountInfo (Weight: 5)
- if need it cancelOrder (Weight: 1)

Which make in the worst case  a Weight of 12.
First question: is the limit weight per binance account or by IP ? and how much Weight is the limit (I didn't really get it from the documentation)

The error says to use websocket, but I didn't found any way to get the Order comission and user balance with websocket.
FYI i wasn't able to get the commission for an order by using getOrder even with the parameter

**Comment by phl3x0r** [comment]
It's per IP. You will get banned for making too many request (weighed) per minute.
Solution:
1: Don't rely on REST API, use WS instead where applicable
2: Use different VPS'es (or IP proxies) for each account
