### ISSUE TITLE
Update Speed for Diff. Depth Stream & Partial Book Depth Streams

### ISSUE THREAD

**Issue by SlicedSilver** [Ashlar/binance-api-node#350]
The Binance WebSockets API supports two different update speeds (100ms and 1000ms) for the following streams:
- Diff. Depth Stream
- Partial Book Depth Streams

Currently this project will only connect at the default speed of 1000ms. Adding `@100ms` to the end of the stream name enables the faster update speed. [reference: Binance docs](https://binance-docs.github.io/apidocs/spot/en/#partial-book-depth-streams)

> Example: `<symbol>@depth<levels>` becomes `<symbol>@depth<levels>@100ms`.

I'm happy to work on a pull request if you could provide some guidance on how you would like the function signatures for `depth` and `partialDepth` to be modified.   
A potential solution which shouldn't cause any breaking changes could be allowing the user to _optionally_ specify the update speed as part of the symbol name. For example: `BTCGBP@100ms` instead of `BTCGBP` when the user wants the faster update speed. It would be trivial to split the symbol name at the `@` symbol and append the second part to the end of the stream name.

**Comment by balthazar** [comment]
I think your idea of having the @100ms part in the symbol directly sounds good! It's backwards compatible and easy to understand, so I'm all for it

**Comment by balthazar** [comment]
0.10.32
