### ISSUE TITLE
@100ms | @1000ms won't work

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [Ashlar/binance-api-node#353]
Hi, 

I took this from your example, it won't load anything ;/
`client.ws.depth('ETHUSDT@100ms', depth => {  console.log(depth) })`

i installed the package trough npm i binance-api-node 
wrong version?

I edited a line in the websocket.js inside node_modules and it seems to work now

`
    var w = (0, _openWebsocket.default)("".concat(variator === 'futures' ? endpoints.futures : endpoints.base, "/").concat(symbol.toLowerCase(), "@depth@100ms"));
`

For partialDepth

`
var w = (0, _openWebsocket.default)("".concat(variator === 'futures' ? endpoints.futures : endpoints.base, "/").concat(symbol.toLowerCase(), "@depth").concat(level)+'@100ms');
`

I'm glad you added this feature!

**Comment by SlicedSilver** [comment]
I submitted the pull request yesterday to add support for `@100ms` as part of the symbol name. Hopefully I didn't introduce a bug but it does seem to be working on my machine. Can you please check that you have the latest version of the package installed? The latest version is `0.10.32`.

The line you referenced within version 0.10.32 looks like this:
```js
var w = (0, _openWebsocket.default)("".concat(variator === 'futures' ? endpoints.futures : endpoints.base, "/").concat(symbolName, "@depth").concat(updateSpeed ? "@".concat(updateSpeed) : ''));
```

**Comment by balthazar** [comment]
@hp8wvvvgnj6asjm7 You shouldn't have to edit anything in the dist. Make sure you are on the latest like @SlicedSilver said.
