### ISSUE TITLE
request to xyz failed, reason: getaddrinfo ENOTFOUND fapi.binance.com

### ISSUE THREAD

**Issue by lsiric** [Ashlar/binance-api-node#355]
Hi,

I am randomly receiving this error when submitting futures api request. Sometimes I can have 10 subsequent requests without the error, and sometimes I get 3-4 of these errors in a row, upon retrying the same request with identical parameters. 

Code example:

```
const client = Binance();
client.futuresCandles({
  symbol: 'BZRXUSDT',
  interval: '4h',
  limit: 200,
});
```

Full error: 

```
FetchError: request to https://fapi.binance.com/fapi/v1/klines?interval=4h&symbol=BZRXUSDT&limit=200 failed, reason: getaddrinfo ENOTFOUND fapi.binance.com
```

This error randomly happens on any symbol, interval and limit parameter value. 

The only repo issue i've found about this is  https://github.com/Ashlar/binance-api-node/issues/254. Unfortunately I'm getting this error on mobile data, adsl, and on 100mbps optic data as well. 

Is this an issue with Binance, the package or I am doing something wrong? 

Thanks and best regards.

**Comment by balthazar** [comment]
Definitely not an error with the lib, looks like a network issue. Make sure not to use a vpn since I know binance has a tendency to block them on some domains

**Comment by lsiric** [comment]
Hi @balthazar , many thanks for quick reply. 
The issue occurs with and without the VPN connection. I am in Europe, so I've tried connecting through Asia/Australia/USA, but still having the same issue.

**Comment by balthazar** [comment]
Not much I can do on my side, I'm just the library author 😄 You can try binance support, they might have more insights
