### ISSUE TITLE
future api and websocket is not working??

### ISSUE THREAD

**Issue by gitsupi** [Ashlar/binance-api-node#360]
all functionality is not working

`
client.allOrders({
    symbol: 'ETHUSDT',
})
    .then(console.log)

client.futuresUserTrades({
    symbol: 'ETHUSDT',
})
    .then(console.log)

// client.ws.depth('ETHBTC', depth => {
//     console.log(depth)
// })

const clean = client.ws.futuresDepth('ETHBTC', depth => {
    console.log(depth)
  }, false)
  // After you're done
  clean()`

**Comment by KarlHeitmann** [comment]
did you get it working? I'm trying to downgrade the version, and I'm on 0.10.5 and it still gives me the same error:

![image](https://user-images.githubusercontent.com/3003032/113525586-b8495480-9583-11eb-9dc0-b56ca626da0f.png)

Uncaught TypeError: rws._ws.on is not a function

**Comment by KarlHeitmann** [comment]
I've solved it by editing the file `open-websocket.js` and commenting out the line

![image](https://user-images.githubusercontent.com/3003032/113528273-1c711600-958e-11eb-97ee-ba6361457237.png)

I don't know why this line of code is present, I took a "sneak peek" at the repo `reconnecting-websocket` and I couldn't figure out what this line is all about.

**Comment by SrBrahma** [comment]
The binance-api-node uses this WebSocket dep: https://github.com/pladaria/reconnecting-websocket/blob/05a2f7cb0e31f15dff5ff35ad53d07b1bec5e197/reconnecting-websocket.ts#L382

The `rws._ws` is a WebSocket object.

![image](https://user-images.githubusercontent.com/28177550/116351113-72219280-a7c9-11eb-914d-817c1c7e9f42.png)

Those above are the properties of a WebSocket object.

Looks like this ping pong is some leftover test code. Should be removed.


@balthazar

**Comment by SrBrahma** [comment]
@balthazar https://github.com/Ashlar/binance-api-node/pull/431 also fixes this. This may be closed

**Comment by balthazar** [comment]
👌🏻
