### ISSUE TITLE
Access to the Spot-Testnet possible?

### ISSUE THREAD

**Issue by dc-deal** [Ashlar/binance-api-node#365]
Hello, is there a possibility to connect to the spot-testnet?
There's is just a slight change in the Endpoint nessecary, i assume.

https://binance-docs.github.io/apidocs/spot/en/#spot-testnet
https://testnet.binance.vision/

**Edit**: I Just discovered that you could easily change API Entry points in your code at
_binance-api-node/src/http-client.js_:

const BASE = 'https://api.binance.com'
const FUTURES = 'https://fapi.binance.com'

To:

https://testnet.binance.vision/api

And in _binance-api-node/src/websocket.js_:

const endpoints = {
  base: 'wss://stream.binance.com:9443/ws',
  futures: 'wss://fstream.binance.com/ws',
}

wss://testnet.binance.vision/ws

_____________________________________________________________
Information from Binance:

Spot API URL | Spot Test Network URL
-- | --
https://api.binance.com/api | https://testnet.binance.vision/api
wss://stream.binance.com:9443/ws | wss://testnet.binance.vision/ws
wss://stream.binance.com:9443/stream | wss://testnet.binance.vision/stream

_______________________________________
Futures Testnet would be here, but i made no research yet.
https://testnet.binancefuture.com/en/futures/BTCUSDT

_______________________

Ok found solution now: you can add "httpBase" to your calls to manipulate api address.
export const BinanceClient = Binance({
    apiKey: BINANCE_API_KEY,
    apiSecret: BINANCE_API_SECRET,
    httpBase : "https://testnet.binance.vision/api"
});

I Didn't see this in your documentation. I kindly ask for adding this. 
Have a great day and thanks for the brilliant module, like it!

**Comment by s709t** [comment]
Yes, this might be good to add it to the documentation

**Comment by balthazar** [comment]
PR's are always welcome.

**Comment by jleskovar** [comment]
Minor correction - the testnet URL should be "https://testnet.binance.vision", as binance-api-node will append the /api suffix
