### ISSUE TITLE
Is it possible to use it against testnet.binance?

### ISSUE THREAD

**Issue by nicosampler** [Ashlar/binance-api-node#367]
Is there a way to configure the lib to run the request against testnet.binance?

It was possible for when I modified this line in `http.client`
 
var BASE = 'https://testnet.binance.vision';

but I could not found a way to set it by an environment variable.

**Comment by EugeneOsadchyi** [comment]
Hi @nicosampler 
Yes, you can.
Just initialize the instance of the module with `httpBase` property.
https://github.com/Ashlar/binance-api-node/blob/master/src/http-client.js#L286
