### ISSUE TITLE
Futures Documentation

### ISSUE THREAD

**Issue by andersonaguiar** [Ashlar/binance-api-node#370]
I noticed that `futuresOrder` is not documented in the README, is there any place where I can find more information about what's available for futures?

**Comment by klemensz** [comment]
Would be interested too... Probably it's a wrapper around https://binance-docs.github.io/apidocs/futures/en/#new-order-trade

**Comment by jstoeffler** [comment]
The documentation for this method is not documented. If this happens the best place to look would be the source code: https://github.com/Ashlar/binance-api-node/blob/master/src/http-client.js

And then you can look at the corresponding endpoint in Binance: https://binance-docs.github.io/apidocs/futures/en/#new-order-trade

+ with typescript you get autocompletion of parameters and results

And if you feel in a good mood you can improve the doc with a PR
