### ISSUE TITLE
Timestamp for this request is outside of the recvWindow

### ISSUE THREAD

**Issue by digimbyte** [Ashlar/binance-api-node#371]
trying to trace where this error originates from
it randomly happens
`node_modules\binance-api-node\dist\http-client.js:93
        error = new Error(json.msg || "".concat(res.status, " ").concat(res.statusText));
                ^

Error: Timestamp for this request is outside of the recvWindow.
    at ...\node_modules\binance-api-node\dist\http-client.js:93:17
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: -1021,
  url: 'https://api.binance.com/api/v3/account?timestamp=1617022581324&signature=1b073************************************68de1'
}`

I also have set a function to manage the local offset without having to resync the OS every 10 minutes
and from what I can tell, it works well.
`getTime: () => (Math.trunc(Date.now() - timeOffset))`
I suspect the error is thrown when this fires at a later time based on my app's logic
`BinanceApp.accountInfo()`

any suggestions or way's to update the time and recvWindow?

**Comment by adriatomas** [comment]
Hi your getTime definition is wrong, the correct way is:
`getTime: () => Date.now()` and will work

**Comment by digimbyte** [comment]
Thanks, but that's the default option which leads to issues if your OS time is out of sync. this also heavily depends on the ability to update and sync the time. my solution is to have the time offset update from the serverTime - local time.
and to use serverTime where possible.
