### ISSUE TITLE
futuresAllForceOrders - Binance endpoint discontinued

### ISSUE THREAD

**Issue by daisy613** [Ashlar/binance-api-node#397]
futuresAllForceOrders relies on the /fapi/v1/allForceOrders endpoint, and that's been discontinued today - any workaround for this?

https://binance-docs.github.io/apidocs/futures/en/#change-log
> 2021-04-27
>     The endpoint GET /fapi/v1/allForceOrders stop being maintained and no longer accepts request.
>

**Comment by Bryan3312** [comment]
I am looking for the same problem. I hope to find some workaround..
