### ISSUE TITLE
Cannot use WebSocket

### ISSUE THREAD

**Issue by xucxichcao** [Ashlar/binance-api-node#404]
I got this error when trying to use ws.futuresUser. I don't know why this is happening.
`Uncaught TypeError: rws._ws.on is not a function
    at eval (open-websocket.js?1ade:31)
    at ReconnectingWebSocket._callEventListener (reconnecting-websocket-mjs.js?d096:555)
    at eval (reconnecting-websocket-mjs.js?d096:167)
    at Array.forEach (<anonymous>)
    at WebSocket.ReconnectingWebSocket._handleOpen (reconnecting-websocket-mjs.js?d096:167)`

**Comment by antichaosdb** [comment]
You get this error because the websocket implementation in the browser doesn't support .on (like server side ones do).  rws.addEventListener in open-websocket.js needs to be changed to this:

rws.addEventListener('open', function () {
    if (rws._ws.on) {
      rws._ws.on('ping', pong);
    }
  });

**Comment by jstoeffler** [comment]
But will that work without responding to the server? If yes it seems like an quick fix

**Comment by balthazar** [comment]
@jstoeffler it might close the connection eventually because of inactivity, but yeah should be better

**Comment by SrBrahma** [comment]
https://github.com/Ashlar/binance-api-node/issues/360#issuecomment-828155963

**Comment by SrBrahma** [comment]
https://binance-docs.github.io/apidocs/spot/en/#websocket-market-streams

Without the pong, the connection will be closed after 10mins.

> because the websocket implementation in the browser doesn't support .on

You sure about this, @antichaosdb? Genuine question. Because reading **websocket** and **ws** npm packages, they use .on everywhere, and I didn't found about them not working in browsers.

**Comment by SrBrahma** [comment]
It looks like a [reconnecting-websocket package limitation](https://github.com/pladaria/reconnecting-websocket/issues/98).

Maybe would be a good idea to use the popular [ws package](https://www.npmjs.com/package/ws)? 34mi monthly downloads vs [58k of the current used one](https://www.npmjs.com/package/reconnecting-websocket).

**Comment by VuongVu** [comment]
@antichaosdb, thanks for your workaround to make it work. I'm new with websocket so I have a question, how can I handle to close the connection? 
Example:
```
useEffect(() => {
        const symbolPrices = data?.map((item) => `${item.token.symbol}USDT`);
        binanceClient.ws.candles(
            symbolPrices ?? [],
            CandleChartInterval.ONE_MINUTE,
            (ticker) => {},
        )

        return () => {
        // Close ws here
        }
    }, [data]);
```

I want to close ws when component unmount, can you give me a solution?

**Comment by SrBrahma** [comment]
> @antichaosdb, thanks for your workaround to make it work. I'm new with websocket so I have a question, how can I handle to close the connection?
> Example:
> 
> ```
> useEffect(() => {
>         const symbolPrices = data?.map((item) => `${item.token.symbol}USDT`);
>         binanceClient.ws.candles(
>             symbolPrices ?? [],
>             CandleChartInterval.ONE_MINUTE,
>             (ticker) => {},
>         )
> 
>         return () => {
>         // Close ws here
>         }
>     }, [data]);
> ```
> 
> I want to close ws when component unmount, can you give me a solution?

```ts
useEffect(() => {
  const unsubscriber = binanceClient.ws.candles(...)
  return () => { unsubscriber() }
}, [...])
```

The ws.candles() returns an unsubscriber function.

**Comment by SrBrahma** [comment]
@balthazar you may close this issue as you merged it. ;)
