### ISSUE TITLE
Question: what happens if websocket connection is dropped?

### ISSUE THREAD

**Issue by ivancsicsmarkus** [Ashlar/binance-api-node#411]
According to binance docs: https://binance-docs.github.io/apidocs/futures/en/#composite-index-symbol-information

"A single connection is only valid for 24 hours; expect to be disconnected at the 24 hour mark"

Should we handle this?

**Comment by ivancsicsmarkus** [comment]
I think it will automatically reconnect because we are using https://github.com/joewalnes/reconnecting-websocket

**Comment by SrBrahma** [comment]
Have you tested this behaviour?
