### ISSUE TITLE
Error due to CORS policy

### ISSUE THREAD

**Issue by firatbulut19** [Ashlar/binance-api-node#414]
I am receiving an error when I try to access signed endpoints. Here is the error:

Access to fetch at [...] from origin [...] has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I use React and here is my source code:

    let time = new Date().getTime()
      const client = Binance({
      apiKey: 'xxx',
      apiSecret: 'xxx',
      getTime: time,
    });
    let assetDetails = await client.assetDetail()

What am I missing?

**Comment by SrBrahma** [comment]
Read this: https://github.com/Ashlar/binance-api-node/issues/37

**Comment by balthazar** [comment]
Binance issue
