### ISSUE TITLE
Futures batchOrders and allOpenOrders endpoints missing

### ISSUE THREAD

**Issue by Fabiansson** [Ashlar/binance-api-node#415]
As far as I know those endpoints are not yet implemented (maybe more):
POST /fapi/v1/batchOrders (HMAC SHA256) 
DELETE /fapi/v1/allOpenOrders (HMAC SHA256) 

Is there any reason for this or just TODO?

Thanks and have a nice one!

**Comment by ivancsicsmarkus** [comment]
Would you mind submitting a PR?
