### ISSUE TITLE
Add LEVERAGED to TradingType enum

### ISSUE THREAD

**Issue by NoUJoe** [Ashlar/binance-api-node#428]
TradingType enum is missing "LEVERAGED" member which is used to determine a leveraged symbol eg. ETHUP/USDT, ETHDOWN/USDT

**Comment by Gsuz** [comment]
I second this.

**Comment by vsly-ru** [comment]
> TradingType enum is missing "LEVERAGED" member which is used to determine a leveraged symbol eg. ETHUP/USDT, ETHDOWN/USDT

@NoUJoe @Gsuz TradingType is a [`SPOT` or `MARGIN`] enum used in the account and symbol permissions. 
I'm unable to find any mentions of word `LEVERAGED` in the official [documentation](https://binance-docs.github.io/apidocs/spot/en/#exchange-information). 
Do you have any references?

**Comment by xiva-wgt** [comment]
check https://api.binance.com/api/v3/exchangeInfo
Symbol "ETHUP/USDT", "ETHDOWN/USDT" have key "permissions":["LEVERAGED"]
official documentation is broken.
