### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by Dikman** [Ashlar/binance-api-node#452]
Hello. I receive "Timestamp for this request was 1000ms ahead of the server's time.".

```js
const Binance = require('binance-api-node').default;

const client = Binance({
  apiKey: xxx,
  apiSecret: xxx,
})

client.getBnbBurn().then(burn => console.log(burn));
```

It worked this morning! But in the evening already do not work.
Help me, please.

**Comment by Dikman** [comment]
Oh. I solved itself. It needed to think a little...

![image](https://user-images.githubusercontent.com/5627946/122099845-24192a80-ce1b-11eb-8c81-3e5029ddf8e1.png)

Sorry and thank you.

**Comment by balthazar** [comment]
🙂
