### ISSUE TITLE
why removed STOP_LOSS_LIMIT/TAKE_PROFIT_LIMIT?

### ISSUE THREAD

**Issue by davidxiao** [Ashlar/binance-api-node#457]
Hi, @malikfaik , mate,
   is there any special reason to remove STOP_LOSS_LIMIT/TAKE_PROFIT_LIMIT types for TS?seem breaking existing code for TS :)
https://github.com/Ashlar/binance-api-node/commit/bfa0b3f1eea1361b30ad78c091109794f0caaf4a

it was removed before, i added it back, and now it's removed again, wonder if there is any reason for that.

Thanks

**Comment by malikfaik** [comment]
No reason from my side, it must have probably gotten removed during the merge. I will add it to enum OrderType.
