### ISSUE TITLE
TS order enums not implemented/exported in JS

### ISSUE THREAD

**Issue by olexme** [Ashlar/binance-api-node#459]
There are some enums defined in index.d.ts which don't have their implementation on JS side.
E.g OrderSide, OrderStatus, OrderType.

**Comment by BusinessDuck** [comment]
`export const enum` should be for OrderType

**Comment by SpekalsG3** [comment]
+1
Reading property 'MARKET' of OrderType throws Error

`Cannot read property 'MARKET' of undefined`

**Comment by YoungNK** [comment]
OrderSide :  Cannot read property 'BUY' of undefined

**Comment by bennycode** [comment]
@olexme when declaring an `enum` in TypeScript it actually generates JavaScript code out of it. So every TS application that uses the enum will have a JS representation of that code. 

Declaring an enum as `const enum` prevents code generation and causes error TS2475. See: https://github.com/Ashlar/binance-api-node/pull/489#issuecomment-965135721
