### ISSUE TITLE
Futures order endpoints

### ISSUE THREAD

**Issue by sintergear** [Ashlar/binance-api-node#461]
Hi, am i right in saying that there are no Futures order endpoints setup? No sign in http-client or the docs for actual placing of orders on the futures side.

**Comment by lucas-labs** [comment]
I haven't actually tested it yet tbh (I'm just starting a new project using this library, so I'm pretty new here), but I think there is a function to place Binance Futures orders. It's called "futuresOrder" and it's inside the http-client.js file:

https://github.com/Ashlar/binance-api-node/blob/84b74987a23512023987c0b38049c2bcd325f7f3/src/http-client.js#L428

So, something like this should work:
```javascript
const binance = binanceApiNode(binanceApiNodeOpts);

binance.futuresOrder(orderOpts);
```

**Comment by sintergear** [comment]
You're right, I missed that. Thanks.
