### ISSUE TITLE
How to stop Web Sockets using clean when instanced

### ISSUE THREAD

**Issue by YasinMC** [Ashlar/binance-api-node#470]
This might be a newbie question but I'm trying to create a proxy WS which will essentially stream the price ticker and close when I send the keyword. but, whenever I try to use clean() it seems to not work

```javascript
app.ws('/ticker', function(ws, req) {
  ws.on('message', function(msg) {
    const clean = client.ws.ticker(msg, ticker => {
      ws.send(JSON.stringify(ticker));
    })
  });
});
```
Basically my question is how can I get the function to stop the stream when for example the msg equals to 'end'. Also I tried using if statement with the ```clean()``` but it only stops the next instance. Really appreciate any help! Thanks for the amazing library

**Comment by vsly-ru** [comment]
The problem seems to be that you declared `const clean` in the local scope of `ws.on('message', ...` function.
Assuming msg is an object, here is a possible solution:
```js
app.ws('/ticker', function (ws, req) {
    let clean;
    ws.on('message', function (msg) {
        if (msg.cmd == 'subscribe') {
            if (clean) clean();  // clean previous subscription if already subscribed
            clean = client.ws.ticker(msg.symbol, ticker => {
                ws.send(JSON.stringify(ticker));
            })
        }
        if (msg.cmd == 'end') {
            if (clean) clean();  // clean the subscription if subscribed
        }
    });
});
```

**Comment by ngdekhai** [comment]
@balthazar Hi, I tried
if(clean) clean(); 
Even after I cleaned the subscription, the clean still return true. Exclude the initial value of clean, it always return true, even after i run clean(); And fyi clean() successfully stopped the websocket.
