### ISSUE TITLE
Maybe you guys wrong here. I cannot call future batchOrders API. Please fix

### ISSUE THREAD

**Issue by pipchris** [Ashlar/binance-api-node#476]
https://github.com/Ashlar/binance-api-node/blob/113ef6b84ac600badade93a3f0ee825c6c96724c/src/http-client.js#L429
I think parameters are wrong place. Please fix. thanks

**Comment by shanaka95** [comment]
@pipchris Did you able to use this without any issue? Can anyone please help

**Comment by pipchris** [comment]
> @pipchris Did you able to use this without any issue? Can anyone please help

@shanaka95 I couldnot use it. so I used another way

**Comment by shanaka95** [comment]
@pipchris How did you achieve that? Can you please help me?

**Comment by pipchris** [comment]
> @pipchris How did you achieve that? Can you please help me?

you can change the code in `node_modules` or order by `loop`. There are just 10 orders that Binance allows us to open

**Comment by shanaka95** [comment]
@pipchris I just need to open 3 orders at once. I tried changing the code in node_modules. Changed the method to POST and it always gives a bad format error. Can you please send me the code to shanaka95@gmail.com

**Comment by pipchris** [comment]
@shanaka95 do you have skype?

**Comment by shanaka95** [comment]
@pipchris Yeah. My Skype ID is shanaka95_1

**Comment by MathewsMarra** [comment]
Hello, I'm having the same problem. Can one of you guys send an code exemple for this function?
