### ISSUE TITLE
All trades from all symbols

### ISSUE THREAD

**Issue by ferranmuntada** [Ashlar/binance-api-node#491]
Hi,
I m starting using that package, and I don't know if it is exist but i cant even find it :(.
Just looking for and endpoint to get all  my trades.  Active, canceled, or filled.
If someone can help me it will be amazing ! 
Thank you so much and sorry for the time

Montix

**Comment by vsly-ru** [comment]
According to the Binance documentation of [Account Trade List](https://binance-docs.github.io/apidocs/spot/en/#account-trade-list-user_data) `symbol` field is **mandatory**.
So you need to iterate thru all of the needed symbols and aggregate trades according to your needs. 
Please also note this endpoint has weight **10** so you can quickly drain your weight [limit](https://binance-docs.github.io/apidocs/spot/en/#limits) resulting in a temporary **IP ban**.

**Comment by ferranmuntada** [comment]
Thank you for the answer @vsly-ru ! 
And there is any way to dodge that weight limit? I'm sure that Ill need to get trades from different symbol field , it means that i will do many calls

**Comment by vsly-ru** [comment]
@ferranmuntada I left the link to the official documentation regarding **limits** right in my answer above. 
This module also provides [getInfo](https://github.com/Ashlar/binance-api-node#getInfo) method which will return currently used limits after you made a request.
