### ISSUE TITLE
Wrong order ids

### ISSUE THREAD

**Issue by yovanoc** [Ashlar/binance-api-node#517]
Because of this JSON.parse:
https://github.com/Ashlar/binance-api-node/blob/3c587efb3800c72730efe34192008f0663b2c6f4/src/http-client.js#L74

We have some wrong order ids.

Idk how to tackle this, maybe use something like json-bigint or whatever but its an important bug for me

ex:

![image](https://user-images.githubusercontent.com/7302317/144256561-cd9ac64d-0ba8-473c-a627-29ca5f31e148.png)

**Comment by balthazar** [comment]
Let me know how it goes in this version

**Comment by yovanoc** [comment]
All went well until now, but happen again once, but usually it was every time

**Comment by yovanoc** [comment]
@balthazar Yes issue still there sometimes

**Comment by yovanoc** [comment]
Idk if its relevant but happen only happen on ETHUSDT x)

**Comment by balthazar** [comment]
Gonna need more info and debug, because I don't see why would it just happen on one pair

**Comment by yovanoc** [comment]
What can I give you more?

**Comment by balthazar** [comment]
Well you need to debug more, if it goes through json-bigint correctly, the problem isn't in binance-api-node. Are you sure it's called etc?

**Comment by yovanoc** [comment]
OHHHH WAIT my bad. Maybe its res.json() too in http requests, but the problem here happened on WS, so this is this line that we need to replace too:

https://github.com/Ashlar/binance-api-node/blob/bdd110717e44078e0e89f250399a0e2619b74691/src/websocket.js#L604

**Comment by balthazar** [comment]
Yup that's exactly what I meant by debug more. If you can open a PR to change all the websocket JSON.parse with json-bigint that would help.

**Comment by yovanoc** [comment]
Yes I will do that in an hour. thanks

**Comment by yovanoc** [comment]
@balthazar Yes I can confirm the problem happen too on the res.json() thing, so what should we do?

**Comment by balthazar** [comment]
You should be able to use res.text() and use bigint there too

**Comment by yovanoc** [comment]
pr done
