### ISSUE TITLE
Cors error in user actions. 

### ISSUE THREAD

**Issue by ugurcanomur** [Ashlar/binance-api-node#522]
I can do normal operations without any problems.

but when I want to do something about the user, I get an error and the result is not returned. 

`
const binanceClient = Binance({
  apiKey: API_KEY,
  apiSecret: SECRET_KEY,
});
`

it returns;

`has been blocked by CORS policy: Request header field x-mbx-apikey is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by balthazar** [comment]
Not a library issue
