### ISSUE TITLE
Feature: Add support for typescript pls 😊

### ISSUE THREAD

**Issue by martudev** [Ashlar/binance-api-node#526]
Hello, how are you? I am developing a bot for binance with your library using typescript and I ran into a problem when executing it that said the following:

![image](https://user-images.githubusercontent.com/55553571/145734905-545d1847-c090-4c13-bafc-1ca80e1f8952.png)

This error is thrown at me when I try to execute the binance.order() function and define an object of the following style inside:
```
const order = await this.binance.order({
	symbol: this.symbol,
	type: OrderType.MARKET,
	side: 'BUY',
	quoteOrderQty: quoteOrderQty.toString(),
});
```
I was investigating the code and I saw that you only upload the index.d.ts but in the src/index.js you do not define the corresponding types, therefore when we compile the code and I need the OrderType it returns undefined and that is why I have that error. It is more if we made a `const { OrderType } = require('binance-api-node')` the OrderType would be undefined since that type would not exist. If you can solve this problem I would appreciate it. Thanks a lot! Greetings Martu

**Comment by balthazar** [comment]
@bennycode

**Comment by bennycode** [comment]
@martudev you can use `OrderType.MARKET` when you import it the following way in your TypeScript app:

```ts
import { OrderType } from 'binance-api-node';
```

**Comment by balthazar** [comment]
Thanks ben

**Comment by balthazar** [comment]
That's not the code benny gave you, so what do you keep on doing something different and then complain it's not working?

**Comment by martudev** [comment]
First of all I am not complaining that it does not work, I am only advising you that for typescript there are things that do not work, it is your decision to want to solve it or not, I would offer to solve it on my own but I really do not have enough time to do it, or it would take a long time, which I don't think is convenient for both of us. I explain the situation to them. I made a bot using its library, but I did it in typescript, therefore I must follow the types defined in index.d.ts as benny said, the problem is that when I compile the code and traspile it with babel it passes all the code to me written in .ts to .js therefore when you execute the code `OrderType.MARKET` and OrderType is not defined anywhere, only in index.d.ts (that this file only does is define the TYPES and only that) it causes me that error. Thanks again for the support. If something is not understood tell me and I'll try to explain

**Comment by bennycode** [comment]
@martudev there must be something wrong with your compiler setup. Your compiler should be smart enough to convert `OrderType.MARKET` into `"MARKET"`. You cannot use `OrderType.MARKET` with JavaScript directly as it is a constant that only exists in TypeScript.

Here is a playground demo which shows you how the compilation works: https://www.typescriptlang.org/play?#code/ATCmA8AcHsCcBdgGNoDsDOjSoK4FtgB5WAE1FgBUBPSUYAbwCgQQAZASQFl2LgBeYAHIO3CoIA0zFiJ4B9TgEEA0gFEASvyEyK85eolSQitat4DBx0wZbAAyhUIAFTYPtPrLN490mVZoV4+VpI2gayEtray2i5hEVHaHiAUerKOaoQAYnIx5imqaRnZOokhLPkqhVlyln4uFVXFQX5JwBRqCuwcAHIA4rKBtf6C7Z09-YMKvmJlAL6MUigY0AA2oAB0K9AA5gAUxGSUNBtDAJQA3EA

![image](https://user-images.githubusercontent.com/469989/145853846-aa0302fa-a9bc-4de8-8a21-71a69094fd25.png)


Are you really sure that you import it in TypeScript as I was suggesting?

**Comment by martudev** [comment]
Hi @bennycode, 
I have been investigating the error more thoroughly, I don't know if you have tried creating a typescript application using its library, but apparently there is an error when using `"moduleResolution": "node"` inside the `tsconfig.json` file. 
When I don't activate the `"moduleResolution": "node"`, then the OrderType.MARKET is converted to string, but i have errors when importing some packages. When I activate it it takes it as a module and tries to access it so i have the error i mention you.

I could not find much information about this problem, so I decided to try to find another solution and it occurred to me to create a string of type OrderType.MARKET, then I managed to solve it that way, the code was something like the following:

```
const order = await this.binance.order({
    symbol: this.symbol,
    type: 'MARKET' as OrderType.MARKET,
    side: 'SELL',
    quantity: quantity.toString(),
});
```

If you want to try the error, I leave you the configurations of my files:

`tsconfig.json`
```
{
    "compilerOptions": {
      "target": "es2021",
      "esModuleInterop": true,
      "allowJs": true,
      "declaration": true,
      "moduleResolution": "node",
      "strict": true,
      "strictPropertyInitialization": false,
      "baseUrl": "./src",
      "outDir": "./dist",
    },
    "include": [
      "./src/**/*"
    ]
}
```

`.babelrc`
```
{
    "presets": [
      ["@babel/env", {
        "targets": {
          "node": 4
        }
      }], "@babel/preset-typescript"
    ],
    "plugins": ["@babel/plugin-transform-runtime"]
}
```

`Build Command I use`
`"build": "npm run clean && tsc && babel src -d dist --extensions \".ts\"",`
