### ISSUE TITLE
Difference between binance-api-node and node-binance-api

### ISSUE THREAD

**Issue by kopax** [Ashlar/binance-api-node#545]
Hello, I want to create a project that communicates with binance API and so far, both client seems actively maintained and it's hard to choose one to start with by just reading the documentation,

- https://www.npmjs.com/package/node-binance-api
- https://www.npmjs.com/package/binance-api-node

Why do you do the work twice and which one do you recommend to use and for which use case ?

**Comment by balthazar** [comment]
It's up to you to chose which one you want to use by researching them and their API. Asking package managers will lead to biased answers, since they will obviously tell your their solution is better than the other, which I will not fall into 😄

**Comment by kopax** [comment]
It's not a trap, I just neeed an advicee to get started with for long term =/.

**Comment by balthazar** [comment]
Not having used the other, it's hard for me to say to be perfectly honest

**Comment by kopax** [comment]
I already choosed yours, because you seem to be more active :) Thanks!

**Comment by kopax** [comment]
![image](https://user-images.githubusercontent.com/1866564/156623391-783b907d-770d-4eb5-8228-e999d0191ee6.png)

I got this after initializing the most basic client this way:

```jx
import Binance from 'binance-api-node'
const client = Binance()

// later
const res = await client.exchangeInfo()
console.log(res)

```

**Comment by balthazar** [comment]
Are you requiring this client side?

**Comment by kopax** [comment]
Yes I am, I will move this server-side when the infra will be delivered.
