### ISSUE TITLE
Return individual WebSocket connections

### ISSUE THREAD

**Issue by bennycode** [Ashlar/binance-api-node#62]
When opening a WebSocket connection, I get a `clean` handle which then can be used to close all open WebSocket connections at once:

```js
return () => cache.forEach(w => w.close(1000, 'Close handle was called', { keepClosed: true }))
```

That's a great encapsulation but it also prevents me from closing individual WebSocket connections.

In my application I am watching the candles of different trading symbols (ETHBTC, BNBBTC, BNTBTC, ...). Sometimes I want to stop watching a symbol (like BNBBTC) but I cannot stop this WebSocket connection without stopping all the others too. We should find a solution to it. WDYT, @balthazar?

**Comment by balthazar** [comment]
Related to #13.

Maybe instead of the simple `clean` callback, we should return an interface that would look like this

```js
{
  socketsBySymbol,
  sockets: cache,
  clean,
}
```

**Comment by bennyn** [comment]
Is `cache` in that case just keeping a reference to all sockets from `socketsBySymbol`?

**Comment by balthazar** [comment]
Cache would be the array of reconnecting websockets as returned by the `.map` [here](https://github.com/HyperCubeProject/binance-api-node/blob/master/src/websocket.js#L33), `socketsBySymbol` should be these same sockets indexed by symbol to allow for easier retrieval (no way to tell which socket is for which pair otherwise, unless you keep track of the index yourself, but that's not really ideal)

**Comment by numerized** [comment]
hello guys I need that too.
Thanks lib is awesome!

**Comment by recidive** [comment]
Just got this problem that the websocket was disconnected and not automatically reconnected. The node.js thread is still blocked but no data is being received, any ideas?

**Comment by balthazar** [comment]
@recidive What version are you using? We recently switch from ws to isomorphic-ws, which could be the issue. Any log output?

**Comment by recidive** [comment]
I'm running 0.10.29. No logs, unfortunately. No exceptions was thrown. Any tips on how to get some logs? I can try to reproduce the problem again. Thanks!

**Comment by balthazar** [comment]
Hum yeah not sure, try to upgrade to the latest maybe and change this

https://github.com/Ashlar/binance-api-node/blob/master/src/open-websocket.js#L8
