### ISSUE TITLE
how to use with proxy ? http_proxy not used

### ISSUE THREAD

**Issue by thechile** [Ashlar/binance-api-node#63]
is it possible to use http proxy with this module ? I tried to use [fetch-with-proxy](https://github.com/touv/node-fetch-with-proxy) but that didn't seem to work either. Any pointers please ? 

thanks.

**Comment by balthazar** [comment]
Because we use the global fetch, this can't work. Maybe you could make a PR to pass a custom instance of `fetch` which would be the module in your case?

**Comment by balthazar** [comment]
This is now part of the lib thanks to #513
