### ISSUE TITLE
Candles WS stream (client.ws.candles) vs. REST (client.candles)

### ISSUE THREAD

**Issue by stylesuxx** [Ashlar/binance-api-node#93]
I have the following question:
When I use the function to get the candles from the REST API the response fields are named differently than the fields I get in the websocket responses.

REST | WS 
 --- | --- 
openTime | startTime
baseAssetVolume | buyVolume
quoteAssetVolume | quoteBuyVolume

and I was wondering if that has a reason? My use case is the following: I first get the last 500 candles via REST, then I subscribe to the websocket. Once a candle is final I want to append it to the candles I gathered before via REST.

And while doing this, I also noticed that when getting the candles via REST, the last attached candle might not be final yet, but this is no where indicated so I could produce an output like that:

Last candle received via REST call:
```
{ openTime: 1525285560000,
    open: '9128.00000000',
    high: '9134.99000000',
    low: '9120.00000000',
    close: '9121.01000000',
    volume: '15.13214700',
    closeTime: 1525285619999,
    quoteVolume: '138058.48264284',
    trades: 99,
    baseAssetVolume: '6.23971100',
    quoteAssetVolume: '56944.13398683' }
```
First candle received via websocket stream that had **isFinal** true:
```
{ startTime: 1525285560000,
  closeTime: 1525285619999,
  open: '9128.00000000',
  high: '9134.99000000',
  low: '9120.00000000',
  close: '9121.11000000',
  volume: '16.25297700',
  trades: 105,
  isFinal: true,
  quoteVolume: '148282.32816881',
  buyVolume: '6.35470200',
  quoteBuyVolume: '57993.63559081' }
```

You can see, open and close times are the same, but the trades, volume, quoteVolume, buyVolume and quoteBuyVolume differ.

I think that it would be a good idea to adjust the naming of the fields, so that they read the same and to add the isFinal flag also to the items that are returned via the REST call.

**Comment by balthazar** [comment]
I tried to follow the same naming conventions as expressed from the docs, but if they are the same it might indeed make sense to unify their names. Not sure about the `isFinal` absent from the REST call though

**Comment by tarkhil** [comment]
And how number of trades in websocket stream can be less than resulting number of trades via REST?
